# Generated by Django 5.1.3 on 2025-05-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='sku',
            field=models.CharField(blank=True, default='0001', max_length=100),
        ),
    ]
