# Generated by Django 5.1.3 on 2025-05-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='0001', max_length=100),
        ),
    ]
